// Verified bibliographic records only. Physical holdings remain zero until staff count them.
export const starterCatalog = [
  {
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    category: 'Classic fiction · Romance',
    isbn: '9780141439518',
    publicationYear: 1813,
    quantity: 0,
    availableQuantity: 0,
  },
  {
    title: 'Frankenstein',
    author: 'Mary Shelley',
    category: 'Gothic fiction · Science fiction',
    isbn: '9780141439471',
    publicationYear: 1818,
    quantity: 0,
    availableQuantity: 0,
  },
  {
    title: 'The Adventures of Sherlock Holmes',
    author: 'Arthur Conan Doyle',
    category: 'Classic fiction · Mystery',
    isbn: '9780141034355',
    publicationYear: 1892,
    quantity: 0,
    availableQuantity: 0,
  },
  {
    title: 'Dracula',
    author: 'Bram Stoker',
    category: 'Gothic fiction · Horror',
    isbn: '9780141439846',
    publicationYear: 1897,
    quantity: 0,
    availableQuantity: 0,
  },
  {
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    category: 'Classic fiction · Literary',
    isbn: '9780743273565',
    publicationYear: 1925,
    quantity: 0,
    availableQuantity: 0,
  },
  {
    title: 'The Hobbit',
    author: 'J. R. R. Tolkien',
    category: 'Fantasy',
    isbn: '9780547928227',
    publicationYear: 1937,
    quantity: 0,
    availableQuantity: 0,
  },
];
